### ISSUE TITLE
Testing API

### ISSUE THREAD

**Issue by challo2018** [ChrisHanuta/velux-klf200-api#1]
Hi Chris, 
thanks a lot for your implementation. I'm trying to test it with my velux rollershutters.
So i added them with the web GUI to the list.

I installed node.js on rasperry pi and then your implementation with npm.

but when i'm trying to run your examples (creatre test.js) and execute it with "node test.js)
there are errors (Example is node 0 wink)

ReferenceError: Net is not defined
    at velux.connect.then.then (/home/pi/test.js:9:35)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)

IP Adresse and WIFI PW is set in your example. Can you give me some hints how to test your implementation on raspberry pi or windows?
Thanks!!

**Comment by PLCHome** [comment]
Sorry, there has probably been a mistake. Net. must be velux.:

'use strict'
const velux = require('velux-klf200-api')
...
return velux.sendCommand({ api: velux.API.GW_GET_ALL_NODES_INFORMATION_REQ })
..

**Comment by PLCHome** [comment]
Thanks!

**Comment by PLCHome** [comment]
Maybe the velux-klf 200 middleware will make your life easier. 
It currently supports only the nodes, but I'm working on the rest. Since I want to include this in the node-red implememtaion.

**Comment by challo2018** [comment]
thanks for your help.
i'm using loxone smarthome. there is a raspberry pi tool called "loxberry" which gives additional features. i'll try to implement the api there to control velux devices with loxone miniserver. but right now i'm first trying to unterstand the api and use it stand anlone.

**Comment by PLCHome** [comment]
No problem. velux-klf200 should serve as an interface between an application and the api. Currently, after setting up the connection, a few settings are made (time and home monitor) and the velux devices (nodes) are queried. Thereafter, the nodes are constantly updated and the application is notified.
If you are interested I can document the interface.
