### ISSUE TITLE
Newer version of KLF API

### ISSUE THREAD

**Issue by andrewfg** [ChrisHanuta/velux-klf200-api#11]
Hi @PLCHome this is just to let you know that there is a newer version of the [technical specification for klf 200 api-ver3-18.pdf](https://github.com/PLCHome/velux-klf200-api/files/5538176/technical.specification.for.klf.200.api-ver3-18.pdf)

**Comment by PLCHome** [comment]
Thanks, I always just checked if there was ever a new firmware. I look at the changes. 

But it won't fix the problems of 0.2.0.0.71.

**Comment by andrewfg** [comment]
> But it won't fix the problems of 0.2.0.0.71.

Indeed :(
