### ISSUE TITLE
rain state

### ISSUE THREAD

**Issue by pergolafabio** [ChrisHanuta/velux-klf200-api#12]
Hi @PLCHome 

can you help me out with a sample script to retrieve the rain sensor state?
it should be available in the 

![image](https://user-images.githubusercontent.com/43251136/121648749-1caef580-ca98-11eb-8526-67bc7671633e.png)
Seems if the Minvalue !=0 , then its raining 

thnx , appreciated!!

**Comment by PLCHome** [comment]
Sorry, I don't have a rain sensor.
Therefore I do not know how this is queried.

**Comment by pergolafabio** [comment]
np, i can try out , but i think i need to send this command? GW_GET_LIMITATION_STATUS_REQ

tried script below, but it gives an error

any idea? not sure how i need to send that command, quite new to this ...

![image](https://user-images.githubusercontent.com/43251136/121654130-b200b880-ca9d-11eb-83ca-840861ea7f9c.png)


```
'use strict'
const velux = require('velux-klf200-api')

velux.on('NTF',(data)=>{
  console.log(data)
})

velux.connect('192.168.0.18',{})
.then(()=>{
  return velux.login('xxx')
})
.then((data)=>{
  return velux.sendCommand({ api: velux.API.GW_GET_LIMITATION_STATUS_REQ  })
})
.then((data)=>{
  console.log(data)
})
.catch((err)=>{
  console.log(err)
  return velux.end()
})
```

**Comment by PLCHome** [comment]
To query the position of a window, the home monitor must be started. Maybe that's the problem here too.

**Comment by pergolafabio** [comment]
the home monitor is started,if i send other commands like this : GW_GET_VERSION_REQ , i get valid output
its because i am also running Home Assistant, that enables the home monitor

i am just not sure how to send those limitation commands

**Comment by PLCHome** [comment]
GW_GET_LIMITATION_STATUS_REQ  has parameter, the call is:
return velux.sendCommand({ api: velux.API.GW_GET_LIMITATION_STATUS_REQ ,    commandOriginator: [int],      priorityLevel: [int],      indexArrayCount: [int],      indexArray: [array of int],      parameterID: [int],      limitationType: [int]   }

**Comment by pergolafabio** [comment]
ah, that makes sense :-)
allthough still stuck, i was told on openhab forums, to check if its raining : 
if minValue !=  => then its rains

so i am not sure if the command aboves will give me the minValue?

any idea how can retrieve that value?
![image](https://user-images.githubusercontent.com/43251136/121671179-89cd8580-caae-11eb-9cc3-058894eaf9f8.png)

**Comment by pergolafabio** [comment]
was trying this command : 

`return velux.sendCommand({ api: velux.API.GW_GET_LIMITATION_STATUS_REQ , commandOriginator: 1, priorityLevel: 2, indexArrayCount: 1, indexArray: 1, parameterID: 0, limitationType: 0 })`

but gives me : 
![image](https://user-images.githubusercontent.com/43251136/121676238-b08eba80-cab4-11eb-9f4d-55c105852fc3.png)

any idea? probably something wrong with the command array maybe? sorry , quite new to this

**Comment by pergolafabio** [comment]
also, if i look in manual, you are talking about a commandoriginator and prioritylevel?
i dont see that? is it possible that your parameters were wrong?

![image](https://user-images.githubusercontent.com/43251136/121677473-319a8180-cab6-11eb-9519-f4b8958e03bc.png)

**Comment by PLCHome** [comment]
I dont know.

**Comment by pergolafabio** [comment]
ok, last question then

how do i need to write this?

`indexArrayCount: [int], indexArray: [array of int],`

for example : 

`indexArrayCount: 2, indexArray: [1,2]`

is that a valid syntax?

**Comment by bergstermann** [comment]
There is an issue in the file klf.js: In line 2002 "27" have to replace with "25"

**Comment by pergolafabio** [comment]
@bergstermann
Ah, do you have it working?
Can you show your code?

**Comment by bergstermann** [comment]
I´m using it in node red.

**Comment by pergolafabio** [comment]
But you have to send the command right? How is your command?

**Comment by bergstermann** [comment]
The parameter in node red:
`{"sessionID":1,"indexArrayCount":1,"indexArray":[0],"parameterID":0,"limitationType":1}`

**Comment by PLCHome** [comment]
> There is an issue in the file klf.js: In line 2002 "27" have to replace with "25"

Fixed

**Comment by pergolafabio** [comment]
Ok, thnx for this, gonna try this later

**Comment by pergolafabio** [comment]
Hey @bergstermann , i was not able to test yet... Have you been able too? What are the values when it's raining/ not raining? Did it also update when the windows was in a closed state?

**Comment by bergstermann** [comment]
It works. 7 percent ist the limitation of window opening by rain. When the window is closed, the limitation is also sent.

**Comment by pergolafabio** [comment]
Cool, do you also use Home Assistant?

**Comment by bergstermann** [comment]
No Redmatic on Homematic CCU3

**Comment by pergolafabio** [comment]
Is 7, is that the value of the ventilation mode? So it only opens to 7% ?

In my case , when it's raining and the windows are closed, then I can't open them, also not in ventilation mode


Do you read out the minvalue ?

**Comment by bergstermann** [comment]
Yes, 7% ist the ventilation mode. LimitationType 0

**Comment by pergolafabio** [comment]
And what is the limitationtype when it's raining? I have heard , if it's NOT 0 , then it means it's raining

**Comment by pergolafabio** [comment]
i have found another github, with python programming, so i am using that one now :)
