### ISSUE TITLE
bug : calling /velux/scenes or /velux/nodes

### ISSUE THREAD

**Issue by s0nik42** [ChrisHanuta/velux-klf200-api#14]
Hi, 

 /velux/nodes or /velux/scenes is not reliable, they can report nothing OR partial result.

In my case : 
```
curl http://localhost:1880/velux/scenes
[]%
curl http://localhost:1880/velux/nodes
[]%
```

But both scenes and nodes can be open/close/execute without problem.

**Comment by PLCHome** [comment]
Do you run the Node Red together with curl or something for this wireless network?

**Comment by PLCHome** [comment]
maybe that's the same:
https://github.com/PLCHome/node-red-contrib-velux/issues/20#issuecomment-1074441363

**Comment by s0nik42** [comment]
I tried with curl yes but on localhost; I will give a try
