### ISSUE TITLE
Problem with login

### ISSUE THREAD

**Issue by golfvert** [ChrisHanuta/velux-klf200-api#3]
Hi,
I have adapted the step example to my situation. I am running 2.0.0.71 and LAN is connected.

I have replaced the IP, put the WiFi password as the 'password' and nevertheless, I can't connect:

Error: refuse login
    at sendCommand.then (/Users/remy/node_modules/velux-klf200-api/lib/net.js:216:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)

Any idea how to debug this?

Thanks for any clue

Rémy

**Comment by PLCHome** [comment]
"Error: refuse login" is the answer for "velux.API.GW_PASSWORD_ENTER_REQ"
The good news is the connection works. 
The message indicates the wrong password. 

- Have you correctly written down the capital letters and small letters from the KLF?
- Is there a web interface on the LAN?
- Maybe the password was changed before or through the update.
- Would you like to reset the KLF to the factory settings?

Debug:
DEBUG=velux-klf200-api:*

**Comment by golfvert** [comment]
> "Error: refuse login" is the answer for "velux.API.GW_PASSWORD_ENTER_REQ"
> The good news is the connection works.
> The message indicates the wrong password.
> 
> * Have you correctly written down the capital letters and small letters from the KLF?
Yes. I have copy/paste the wifi password in the file.

> * Is there a web interface on the LAN?
No. But, as far as I know it is expected.

> * Maybe the password was changed before or through the update.
The Wifi password is the same... When I disconnect the LAN I can still connect using the KLF access-point. So, I guess at least this one has not changed!

> * Would you like to reset the KLF to the factory settings?
I can do that. I will and report back.

> 
> Debug:
> DEBUG=velux-klf200-api:*
This is where my node.js knowledge stops! I don't know where to put this DEBUG... In the js file it doesn't work.

Thanks for helping.

**Comment by golfvert** [comment]
The reset to factory did the trick! I pushed back all the configuration from one KLR and it worked!
Is this box a bit temperamental !?
Great job for the API. Thank you.

**Comment by PLCHome** [comment]
> Is there a web interface on the LAN?
Sorry was a trick question, I wanted to know if really the latest software is running.


This with the debug depends on the operating system. 
There are so-called environment variables. The DEBUG variable must be set, then node.js debug messages explode on the console.
For Windows, just before starting node.js with the set DEBUG command, the environment variable must be set in the verbal console / batch.
Under Linux, the set is omitted.

Debugging in the API outputs all data packages and method calls with the transfer parameters.

I am glad that it works for you now. If you have any questions, I am here.
