### ISSUE TITLE
ReadMe Issue: functionalParameterMPValue

### ISSUE THREAD

**Issue by StefanHaring** [ChrisHanuta/velux-klf200-api#4]
Hi, 

there is a short mistake in the sample code:
"functionalParameterMPValue: {valueType:'RELATIVE', value:100)," should be changed to "functionalParameterMP: {valueType:'RELATIVE', value:100},"

Best regards,
Stefan

**Comment by PLCHome** [comment]
Yes correct is:
functionalParameterMP: {valueType:'RELATIVE', value:100),
      /* functionalParameterMP: 100, */

**Comment by StefanHaring** [comment]
One small additional thing: ")" after 100 also has to be changed to "}".
