### ISSUE TITLE
Position FeedBack?

### ISSUE THREAD

**Issue by Missenberger79** [ChrisHanuta/velux-klf200-api#9]
Hi, 
great Interface to the KLF200.

I can control 2 shutters and 1 window opener. 

But i didnt found a solution in the API to get the Feedback for the real Position if someone use the original Remotecontrol or the Rain close the window.

Did the interface provide a PositionFeedback and Rain (True/False)?

In the NodeRed Node there are Datapoint for the Position but without a Value. 

So i Think the KLF can deliver a Position. I am right?

**Comment by PLCHome** [comment]
Sorry I only saw the question now.
Querying the position works via the home monitor function. However, the KLF can crash due to a firmware error.

> In the NodeRed Node there are Datapoint for the Position but without a Value.
![image](https://user-images.githubusercontent.com/29116097/91137142-cf9b9780-e6ae-11ea-9ee8-252c28bba2a7.png)
